name: blog_project_build

volumes:
  db_blog_data:
  media:
  static:

services:

  blog_db:
    image: postgres:17
    env_file: .env
    volumes:
      - db_blog_data:/var/lib/postgresql/data

  blog_backend:
    build: ./backend/
    env_file: .env
    volumes:
      - media:/blog_app/media
      - static:/blog_app/collectedstatic
    depends_on:
      - blog_db

  blog_gateway:
    build: ./gateway/
    volumes:
      - media:/media
      - static:/static
    ports:
      - 8000:80 