# Generated by Django 5.1.4 on 2025-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_author_alter_blogger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
